In [19]:
# Первая система уравнений
import numpy as np

arr = np.matrix([ [2,1,0], [1,0,3], [0,5,-1] ])
arrx = np.matrix([ [5,1,0], [16,0,3], [10,5,-1] ])
arry = np.matrix([ [2,5,0], [1,16,3], [0,10,-1] ])
arrz = np.matrix([ [2,1,5], [1,0,16], [0,5,10] ])
arr_answers = np.matrix([ [5],[16],[10]])
arr_inverse = np.linalg.inv(arr)

det_manual = ( (arr[0,0] * arr[1,1] * arr[2,2]) + (arr[0,1] * arr[1,2] * arr[2,0])
             + (arr[0,2] * arr[1,0] * arr[2,1]) - (arr[0,2] * arr[1,1] * arr[2,0]) 
             - (arr[0,1] * arr[1,0] * arr[2,2]) - (arr[0,0] * arr[1,2] * arr[2,1]) )
             # = -29
det_function = float( format(np.linalg.det(arr), '0.1f') ) # = -29.0
det_x = np.linalg.det(arrx) # Не будем второй раз писать всё в ручную
det_y = np.linalg.det(arry) # Воспользуемся встроенной функцией det()
det_z = np.linalg.det(arrz) # Из библиотеки numpy

x1,y1,z1 = det_x / det_manual,   det_y / det_manual,   det_z / det_manual
x2,y2,z2 = det_x / det_function, det_y / det_function, det_z / det_function
X = arr_inverse * arr_answers
ans = [['Manual answers', x1,y1,z1], ['Function answers',x2,y2,z2]]
for i in range(len(ans)):
    for j in range(1,4):    
        ans[i][j] = float( format( ans[i][j], '0.1f'))
for i in ans: print(i)
print('Answer by using inverse:\n',X)

['Manual answers', 1.0, 3.0, 5.0]
['Function answers', 1.0, 3.0, 5.0]
Answer by using inverse:
 [[1.]
 [3.]
 [5.]]


In [20]:
# Вторая система уравнений
import numpy as np

arr = np.matrix([  [1,1,-2], [2,3,-7],  [5,2,1] ])
arrx = np.matrix([ [6,1,-2], [16,3,-7], [16,2,1] ])
arry = np.matrix([ [1,6,-2], [2,16,-7], [5,16,1] ])
arrz = np.matrix([ [1,1,6],  [2,3,16],  [5,2,16] ])
arr_answers = np.matrix([ [6],[16],[16]])
arr_inverse = np.linalg.inv(arr)

det_manual = ( (arr[0,0] * arr[1,1] * arr[2,2]) + (arr[0,1] * arr[1,2] * arr[2,0])
             + (arr[0,2] * arr[1,0] * arr[2,1]) - (arr[0,2] * arr[1,1] * arr[2,0]) 
             - (arr[0,1] * arr[1,0] * arr[2,2]) - (arr[0,0] * arr[1,2] * arr[2,1]) )
             # = -29
det_function = float( format(np.linalg.det(arr), '0.1f') ) # = -29.0
det_x = np.linalg.det(arrx) # Не будем второй раз писать всё в ручную
det_y = np.linalg.det(arry) # Воспользуемся встроенной функцией det()
det_z = np.linalg.det(arrz) # Из библиотеки numpy

x1,y1,z1 = det_x / det_manual,   det_y / det_manual,   det_z / det_manual
x2,y2,z2 = det_x / det_function, det_y / det_function, det_z / det_function
X = arr_inverse * arr_answers
ans = [['Manual answers', x1,y1,z1], ['Function answers',x2,y2,z2]]
for i in range(len(ans)):
    for j in range(1,4):    
        ans[i][j] = float( format( ans[i][j], '0.1f'))
for i in ans: print(i)
print('Answer by using inverse:\n',X)

['Manual answers', 3.0, 1.0, -1.0]
['Function answers', 3.0, 1.0, -1.0]
Answer by using inverse:
 [[ 3.]
 [ 1.]
 [-1.]]


In [1]:
# Третье задание, с матрицей с тригонометрическими функциями
import sympy as sp 
import numpy as np
import random

phi = random.randint(0,1000)
Trig_matrix = np.matrix( [ [sp.cos(phi), -sp.sin(phi)], 
                           [sp.sin(phi),  sp.cos(phi)] ])
print(Trig_matrix)

det = (Trig_matrix[0,0] * Trig_matrix[1,1]) - (Trig_matrix[0,1] * Trig_matrix[1,0])

print(det, ' = ', sp.N(det)) # Counting the result of expression
print('                OR ')
print(det, ' = ', sp.trigsimp(det)) # Simplifying the expression


[[cos(335) -sin(335)]
 [sin(335) cos(335)]]
cos(335)**2 + sin(335)**2  =  1.00000000000000
                OR 
cos(335)**2 + sin(335)**2  =  1


In [78]:
#import sympy as sp 

#print( (sp.N( sp.sin( 1.57 )) ) ) # N() - returns numeral value
#print( sp.N(        sp.sin(1)**2 + sp.cos(1)**2 ) ) # Equals 1.000000000...
#print( sp.trigsimp( sp.sin(1)**2 + sp.cos(1)**2 ) ) # Equals exactly to 1


In [8]:
# Попытка автоматизации решения путем принятия на вход значений из 
# системы уравнений путём ввода пользователем соответствующих
# значений в окно запроса функции input()
import numpy as np

arr = np.matrix( [ [None,None,None,None,None], 
                   [None,None,None,None,None],
                   [None,None,None,None,None], 
                   [None,None,None,None,None],
                   [None,None,None,None,None] ])
print(arr)
print('Введите значения первого уравнения через пробел')
a = input()
res = a.split()
for i in range(5):
    for j in range(5):
        if (i*5 + j + 1) > len(res): break
        else:
            arr[i,j] = int(res[ i*5 + j ])
print(arr)

[[None None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]]
Введите значения первого уравнения через пробел
[[1 2 3 4 5]
 [None None None None None]
 [None None None None None]
 [None None None None None]
 [None None None None None]]
