In [5]:
# 1
import numpy as np
from sympy import *
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d



In [9]:
# #1
# XA = B
# X = B * A^-1
A = np.matrix([[2, -3], [1, 4]])
B = np.matrix([[-1, 2], [0, 5],[3,-1]])
X = B.dot(np.linalg.inv(A))
print(X)
print(X.dot(A))
print(B)
print("ВЕРНО")

[[-0.54545455  0.09090909]
 [-0.45454545  0.90909091]
 [ 1.18181818  0.63636364]]
[[-1.  2.]
 [ 0.  5.]
 [ 3. -1.]]
[[-1  2]
 [ 0  5]
 [ 3 -1]]


In [6]:
# #2

# x^2 / 4 + z^2 / 4 - y^2 / 9 = -1
# - x^2 / 4 - z^2 / 4 + y^2 / 9 = 1
# y^2 = 9* (1 + x + z)
x = np.linspace(-10, 10, 1000)
z = np.linspace(-10, 10, 1000)
[x, z] = np.meshgrid(x, z)
y1 = lambda x, z:  9 * np.sqrt((1 + x**2/4 + z**2/4))
y2 = lambda x, z: -9 * np.sqrt((1 + x**2/9 + z**2/4))
Z1 = y1(x, z)
Z2 = y2(x, z)
fig = plt.figure(figsize=(10, 10))
ax = plt.axes(projection='3d')
my_cmap = plt.get_cmap('magma')
surf1 = ax.plot_surface(x, z, Z1, rstride = 8, cstride = 8, alpha=0.8, cmap=my_cmap)
surf2 = ax.plot_surface(x, z, Z2, rstride = 8, cstride = 8, alpha=0.8, cmap=my_cmap)


In [17]:
# #3

A = np.array([[1,-2,1,1], [1,-2,1,-5], [1,2,1,13]])
# СТРОКИ ЛЗ !
# (3) = -2*(2) + 3*(1)
# Тогда можно выращить только х_4 = 1/3
# Тогда x_1 - 2*x_2 + x_3 = 2/3
B = np.array([1,-1,5])
D = np.column_stack((A,B))
rank_A = np.linalg.matrix_rank(A)
rank_D = np.linalg.matrix_rank(D)
print(rank_A, "=", rank_D, "=>", rank_D == rank_A)
print(D, '\n')

print( [1/3,0,1/3,1/3])
print('ИЛИ')
print([2/3, 0, 0, 1/3])

3 = 3 => True
[[ 1 -2  1  1  1]
 [ 1 -2  1 -5 -1]
 [ 1  2  1 13  5]] 

[0.3333333333333333, 0, 0.3333333333333333, 0.3333333333333333]
ИЛИ
[0.6666666666666666, 0, 0, 0.3333333333333333]


In [18]:
# #4
'''
{x - y + 4z - 6 = 0
{2x + y - z + 3 = 0
----
3x + 3z - 3 = 0
x + z = -1
'''
# Plane : 3x + y - 4z - 15 = 0
P = Plane(Point3D(5,0,0),Point3D(0,15,0),Point3D(0,0,-15/4))
L = Line(Point3D(0,0,-1), Point3D(-1,0,0))
angle = P.angle_between(L)
print(angle)
print("Угол != 0 => пересекаются")

asin(7*sqrt(13)/26)
