In [1]:
# Теорема Кронекера-Капелли

# Система из n-уравнений и n-неизвестных

In [3]:
import numpy as np

# 4x_1 + 3x_2 + 2x_3 =  25
#-2x_1 + 2x_2 + 3x_3 = -10
# 3x_1 - 5x_2 + 2x_3 = -4

A = np.array([[4,3,2], [-2,2,3], [3,-5,2]])
B = np.array([25,-10,-4])
D = np.column_stack((A,B))
rank_A = np.linalg.matrix_rank(A)
rank_D = np.linalg.matrix_rank(D)
print(D)
print(rank_A, rank_D) # Rank = 3, Variables = 3 => 1 solution
# det A != 0 => rank_A = 3

X = np.linalg.inv(A).dot(B) # 5 3 -2
#X = np.linalg.solve(A,B)
print(X)

[[  4   3   2  25]
 [ -2   2   3 -10]
 [  3  -5   2  -4]]
3 3
[ 5.  3. -2.]


In [4]:
A = np.matrix([[1,-2,0,1], [3,-1,-2,0], [2,1,-2,-1], [1,3,-2,-2]])
A_ = np.array([[1,-2,0,1], [0,5,-2,-3], [0,5,-2,-3], [0,5,-2,-3]])
B = np.array([-3,1,4,7])
B_ = np.array([-3,10,10,10])
D = np.column_stack((A,B))
D_ = np.column_stack((A_, B_))
rank_A = np.linalg.matrix_rank(A)
rank_D = np.linalg.matrix_rank(D)
#print(D)
#print(D_)



from sympy import *
A = Matrix([[1,-2,0,1], [3,-1,-2,0], [2,1,-2,-1], [1,3,-2,-2]])
RA = A.rref()
print(RA)
#print(help(Matrix))

x1, x2, x3, x4 = symbols('x1 x2 C1 C2')
B = Matrix([-3,1,4,7])
X = linsolve((A,B), x1,x2,x3,x4)
print(X)
X = Matrix([[4*x3/5 + x4/5 + 1], [2*x3/5 + 3*x4/5 + 2], [x3], [x4]])
print(A * X == B)


(Matrix([
[1, 0, -4/5, -1/5],
[0, 1, -2/5, -3/5],
[0, 0,    0,    0],
[0, 0,    0,    0]]), (0, 1))
{(4*C1/5 + C2/5 + 1, 2*C1/5 + 3*C2/5 + 2, C1, C2)}
True


In [33]:
A = Matrix([[1,3,4,-2], [0,5,7,-4], [1,8,11,-6], [-1,2,3,-2]])
RA = A.rref()
print(A.rank())

E = A.nullspace() # ФУНДАМЕНТАЛЬНОЕ РЕШЕНИЕ
print(E, '\n')

# => Rank = 2 =>
C1, C2 = symbols('C1 C2')
X = C1 * E[0] + C2 * E[1]
print('Общее решение системы уравнений: ',X)
# Решение (0,0,0,0) - ТРИВИАЛЬНОЕ

2
[Matrix([
[ 1/5],
[-7/5],
[   1],
[   0]]), Matrix([
[-2/5],
[ 4/5],
[   0],
[   1]])] 

Общее решение системы уравнений:  Matrix([[C1/5 - 2*C2/5], [-7*C1/5 + 4*C2/5], [C1], [C2]])


In [34]:
# Д/З :
# 2.193, 2.194, 2.208, 2.209, 2.227, 2.228

In [36]:
# 2.193

A = np.array([[4,4,5,5], [2,0,3,-1], [1,1,-5,0], [0,3,2,0]])
B = np.array([0,10,-10,1])
D = np.column_stack((A,B))
rank_A = np.linalg.matrix_rank(A)
rank_D = np.linalg.matrix_rank(D)
print(D, '\n')

X = np.linalg.inv(A).dot(B)
print(X)

[[  4   4   5   5   0]
 [  2   0   3  -1  10]
 [  1   1  -5   0 -10]
 [  0   3   2   0   1]] 

[ 1. -1.  2. -2.]


In [47]:
# 2.194

A = np.array([[2,-1,3,2], [3,3,3,2], [3,-1,-1,-2], [3,-1,3,-1]])
B = np.array([4,6,6,6])
D = np.column_stack((A,B))
rank_A = np.linalg.matrix_rank(A)
rank_D = np.linalg.matrix_rank(D)
print(D, '\n')

X = np.linalg.inv(A).dot(B)
Ans = []
for i in X:
    Ans.append(f'{i : 0.1f}')
print(Ans)

[[ 2 -1  3  2  4]
 [ 3  3  3  2  6]
 [ 3 -1 -1 -2  6]
 [ 3 -1  3 -1  6]] 

[' 2.0', '-0.0', ' 0.0', ' 0.0']


In [48]:
# 2.208

A = np.array([[3,-2,-5,1], [2,-3,1,5], [1,2,0,-4], [1,-1,-4,9]])
B = np.array([3,-3,-3,22])
D = np.column_stack((A,B))
rank_A = np.linalg.matrix_rank(A)
rank_D = np.linalg.matrix_rank(D)
print(D, '\n')

X = np.linalg.inv(A).dot(B)
Ans = []
for i in X:
    Ans.append(f'{i : 0.1f}')
print(Ans)

[[ 3 -2 -5  1  3]
 [ 2 -3  1  5 -3]
 [ 1  2  0 -4 -3]
 [ 1 -1 -4  9 22]] 

['-1.0', ' 3.0', '-2.0', ' 2.0']


In [10]:
# 2.209

A = np.array([[1,1,-6,-4], [3,-1,-6,-4], [2,3,9,2], [3,2,3,8]])
B = np.array([6,2,6,-7])
D = np.column_stack((A,B))
rank_A = np.linalg.matrix_rank(A)
rank_D = np.linalg.matrix_rank(D)
print(D, '\n')

X = np.linalg.inv(A).dot(B)
Ans = []
for i in X:
    Ans.append(f'{i : 0.3f}')
print(Ans)

[[ 1  1 -6 -4  6]
 [ 3 -1 -6 -4  2]
 [ 2  3  9  2  6]
 [ 3  2  3  8 -7]] 

['-0.000', ' 2.000', ' 0.333', '-1.500']


In [53]:
# № 2.227

A = Matrix([[1,2, 4,-3], 
            [3,5, 6,-4], 
            [4,5,-2, 3], 
            [3,8,24,-19]])
RA = A.rref()
print(A.rank())

E = A.nullspace() # ФУНДАМЕНТАЛЬНОЕ РЕШЕНИЕ
print(E, '\n')

# => Rank = 2 =>
C1, C2 = symbols('C1 C2')
X = C1 * E[0] + C2 * E[1]
print('Общее решение системы уравнений: ',X)
# Решение (0,0,0,0) - ТРИВИАЛЬНОЕ

2
[Matrix([
[ 8],
[-6],
[ 1],
[ 0]]), Matrix([
[-7],
[ 5],
[ 0],
[ 1]])] 

Общее решение системы уравнений:  Matrix([[8*C1 - 7*C2], [-6*C1 + 5*C2], [C1], [C2]])


In [8]:
# № 2.228

A = Matrix([[2,-4, 5, 3], 
            [3,-6, 4, 2], 
            [4,-8,17,11]])
RA = A.rref()
print(A.rank(), '\n')

E = A.nullspace() # ФУНДАМЕНТАЛЬНОЕ РЕШЕНИЕ
print(E, '\n')

# => Rank = 2 =>
C1, C2 = symbols('C1 C2')
X = C1 * E[0] + C2 * E[1]
print('Общее решение системы уравнений: ',X)

# Решение (0,0,0,0) - ТРИВИАЛЬНОЕ

2 

[Matrix([
[2],
[1],
[0],
[0]]), Matrix([
[ 2/7],
[   0],
[-5/7],
[   1]])] 

Общее решение системы уравнений:  Matrix([[2*C1 + 2*C2/7], [C1], [-5*C2/7], [C2]])


In [58]:
A = Matrix([[2,-4, 5, 3], 
            [3,-6, 4, 2], 
            [4,-8,17,11]]) # Тут ЛК-ции неизвестных
B = Matrix([0,0,0])     # Чему равны эти ЛК
RA = A.rref()

x1, x2, x3, x4 = symbols('x1 C1 x3 C2')
X = linsolve((A,B), x1,x2,x3,x4)

sX = str(X)[2:-2]
sX = sX.replace('C1','x2')
sX = sX.replace('C2','x4')

print('Общее решение системы уравнений: ')
print(sX)
X = Matrix([[2*x2 + 2*x4/7], [x2], [-5*x4/7], [x4]])
print(A * X == B)

Общее решение системы уравнений: 
2*x2 + 2*x4/7, x2, -5*x4/7, x4
True
