In [25]:
x=2*3

In [26]:
k=3+4 #Вводим переменную
print(k) #Выводим значение переменной на экран

7


In [27]:
(k+1)*(k-1)

48

In [28]:
(x+1)*(x-1)

35

In [39]:
# УПРАЖНЕНИЕ 2
# Выводим данные о всех введенных переменных
# Затем убираем все переменные
# Проверяем, удалились ли переменные

In [32]:
%whos

Variable   Type       Data/Info
-------------------------------
Pi_Vs      ndarray    6: 6 elems, type `float64`, 48 bytes
Values     ndarray    9: 9 elems, type `float64`, 72 bytes
k          int        7
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
value      float64    2.0
x          int        6


In [34]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [35]:
%whos

Interactive namespace is empty.


In [40]:
# УПРАЖНЕНИЕ 3
x,y,z,t=1,2,3,4 #Вводим новые переменные
%whos

Variable   Type    Data/Info
----------------------------
t          int     4
x          int     1
y          int     2
z          int     3


In [38]:
del(x) #Удаляем из памяти конкретную переменную
%whos

Variable   Type    Data/Info
----------------------------
t          int     4
y          int     2
z          int     3


$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$

In [41]:
import numpy as np
B = np.array( [1, 3,-1] ) #Создаем вектор-строку
print(B)

[ 1  3 -1]


In [42]:
import numpy as np
A = np.array( [ [1, 2, 3, 4], [0, 1, 3, 2] ] ) #Матрица 4х2
print(A)

[[1 2 3 4]
 [0 1 3 2]]


In [20]:
print(A[:,0]) # столбец
print(A[1:,]) # строка

[1 0]
[[0 1 3 2]]


In [21]:
v = np.arange(1,8,2) # Генератор
print(v)

[1 3 5 7]


In [44]:
import numpy as np
A = np.arange(4)
print('A=', A)
B = np.arange(12).reshape(2,6) # Создаём матрицу 6х2 при помощи
                               # генератора и изменения формы
print('B=', B)

A= [0 1 2 3]
B= [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [45]:
print(np.shape(A)) # вЫводим форму матрицы А

(4,)


In [46]:
# Используем нестандартные значения, введённые при помощи
# математических функция библиотеки numpy
import numpy as np
S = np.array( [-1, np.sqrt(2), np.abs(-3)] )
print(S)

[-1.          1.41421356  3.        ]


In [26]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [ ]:
#УПРАЖНЕНИЕ 4

$\begin{bmatrix} 0 & 1 & 2 & 3 \\ 4 & 5 & 6 & 7 \\ 8 & 9 & 10 & 11 \end{bmatrix}$

In [47]:
import numpy as np
# Задаём матрицу размером 4х3
R = np.array( [ [0,1,2,3], [4,5,6,7], [8,9,10,11] ] )
print(R)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
#ПУНКТ 2
R[2,3] = -R[2,3]
print(R)

[[ 0  6 -6  9]
 [ 4 10  6  7]
 [ 8 18 10 11]]


In [37]:
R[0,2] -= 4
print(R)

[[  0   6 -10   9]
 [  4  10   6   7]
 [  8  18  10  11]]


In [38]:
for i in range(3):
    R[i,1] *= 2
for i in range(4):
    R[0,i] *= 3
print(R)

[[  0  36 -30  27]
 [  4  20   6   7]
 [  8  36  10  11]]


In [48]:
# ПУНКТ 3
v_line_1 = [0]*5
v_line_2 = [0]*7
v_etc_1 = [ [0] ] * 2
v_etc_2 = [ [0] ] * 5
v_etc_3 = [ [0] ] * 7 
print(v_line_1)
print(v_etc_1)
# УПРАЖНЕНИЕ ВЫПОЛНЕНО

[0, 0, 0, 0, 0]
[[0], [0]]


In [43]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [42]:
#УПРАЖНЕНИЕ 5

In [50]:
# ПУНКТ 1
import numpy as np
import numpy.matlib
A = np.matlib.matrix('1, 2, 3; 4, 5, 6')
B = np.matlib.matrix('1, -2, 1; -2, 3, 4')
c = 2
D = np.matlib.ones((2,3))
E = np.matlib.eye(3,3)

In [51]:
print(A)
print(B)
print(c)
print(D)
print(E)

[[1 2 3]
 [4 5 6]]
[[ 1 -2  1]
 [-2  3  4]]
2
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
# ПУНКТ 2
print(A+B)

[[ 2  0  4]
 [ 2  8 10]]


In [53]:
print(A+c)

[[3 4 5]
 [6 7 8]]


In [54]:
#print(A+E) # INVALID, different shapes

In [55]:
print(A-B)

[[0 4 2]
 [6 2 2]]


In [56]:
print(A-c)

[[-1  0  1]
 [ 2  3  4]]


In [69]:
print(c*A)

[[ 2  4  6]
 [ 8 10 12]]


In [57]:
#print(A*B) # ERROR 
# НЕСООТВЕТСТВИЕ ПРАВИЛУ ПЕРЕМНОЖЕНИЯ МАТРИЦ

In [68]:
help (np.fabs)

Help on ufunc:

fabs = <ufunc 'fabs'>
    fabs(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Compute the absolute values element-wise.
    
    This function returns the absolute values (positive magnitude) of the
    data in `x`. Complex values are not handled, use `absolute` to find the
    absolute values of complex data.
    
    Parameters
    ----------
    x : array_like
        The array of numbers for which the absolute values are required. If
        `x` is a scalar, the result `y` will also be a scalar.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This 

In [71]:
import numpy as np
x = np.array([[1,3,4],[6,1,0]])
A=np.sin(x)
print(A)

[[ 0.84147098  0.14112001 -0.7568025 ]
 [-0.2794155   0.84147098  0.        ]]


In [73]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [72]:
#УПРАЖНЕНИЕ 7

In [58]:
import numpy as np
V = np.array( [1,3,5] ) # Вводим изначальные числа
V_roots = np.sqrt(V) 
# Получаем новый массив с корнями чисел из первого
print(V_roots)
# ГОТОВО

[1.         1.73205081 2.23606798]


In [78]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [77]:
# C1

In [59]:
import numpy as np
V_1 = np.arange(-2,11,2) # Задаём вектор-строку при помощи генератора
V_1 *= 3                 #Утраиваем все элементы в вектор-строке
print(V_1)
V_2 = np.arange(45,4,-5) # Задаём вектор-строку
print(V_2.size) # Выводим размерность вектор-строки

[-6  0  6 12 18 24 30]
9


In [82]:
# C2

In [10]:
#Первое задание
import numpy as np
Pi_Vs = np.array( [0, np.pi / 6, np.pi / 3, np.pi / 2, np.pi, 2*np.pi] )
#Записали значения углов в радианах
for value in Pi_Vs:
    print(f'\nCosine, Sine, Tangent for {value} equals:')
    print(np.cos(value), np.sin(value), np.tan(value))
#Вывели все значения тригонометрических функций для заданных углов


Cosine, Sine, Tangent for 0.0 equals:
1.0 0.0 0.0

Cosine, Sine, Tangent for 0.5235987755982988 equals:
0.8660254037844387 0.49999999999999994 0.5773502691896257

Cosine, Sine, Tangent for 1.0471975511965976 equals:
0.5000000000000001 0.8660254037844386 1.7320508075688767

Cosine, Sine, Tangent for 1.5707963267948966 equals:
6.123233995736766e-17 1.0 1.633123935319537e+16

Cosine, Sine, Tangent for 3.141592653589793 equals:
-1.0 1.2246467991473532e-16 -1.2246467991473532e-16

Cosine, Sine, Tangent for 6.283185307179586 equals:
1.0 -2.4492935982947064e-16 -2.4492935982947064e-16


In [12]:
#Второе задание
import numpy as np
Values = np.arange(-2,2.5,0.5) #Получаем нужные значения с помощью генератора
for value in Values:
    print(f'Value: {value} | Result: { (np.cosh(value))**2 - (np.sinh(value))**2 }')
#Выводим итог на экран          

Value: -2.0 | Result: 1.0000000000000018
Value: -1.5 | Result: 1.0000000000000009
Value: -1.0 | Result: 1.0000000000000002
Value: -0.5 | Result: 0.9999999999999998
Value: 0.0 | Result: 1.0
Value: 0.5 | Result: 0.9999999999999998
Value: 1.0 | Result: 1.0000000000000002
Value: 1.5 | Result: 1.0000000000000009
Value: 2.0 | Result: 1.0000000000000018


In [ ]:
# ТРЕТЬЕ ЗАДАНИЕ
# 1) Имена переменных начинаются с буквы
#    максимальная длина - 63 символа
#    можно использовать символы подчёркивания, цифры, большие и 
#    малые буквы латиницы
# 2) Информацию о переменных рабочего пространства можно получить
#    с помощью команды "%whos"
# 3) Подробную информацию о функции или команде можно получить, 
#    написав "help (*имя_функции*)"
# 4) Матрицу произвольной размерности можно задать, используя
#    массив с данными, применив к нему функцию np.reshape(x,y) 
#    из библиотеки numpy
# 5) С помощью соответствующих знаков математических операций:
#    +   -   *    /

# ВЫВОД: На этой лабораторной работе мы повторили основы синтаксиса python, научились пользоваться библиотекой numpy.